<?php

namespace App\Command;

use App\Entity\Ville;
use App\Repository\VilleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(
    name: 'app:seed-villes',
    description: 'Insère les villes (distances voiture depuis Melun) dans la table ville.',
)]
class SeedVillesCommand extends Command
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        private readonly VilleRepository $villeRepository,
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        // Clé nom|département déjà en base (idempotence).
        $existants = [];
        foreach ($this->villeRepository->findAll() as $ville) {
            $existants[$ville->getNom() . '|' . $ville->getDepartement()] = true;
        }

        $ajoutees = 0;
        $ignorees = 0;

        foreach (self::getVilles() as [$nom, $kilometres, $departement]) {
            $cle = $nom . '|' . $departement;
            if (isset($existants[$cle])) {
                ++$ignorees;
                continue;
            }
            $existants[$cle] = true;

            $ville = new Ville();
            $ville->setNom($nom);
            $ville->setDepartement($departement);
            $ville->setKilometres($kilometres);
            $this->entityManager->persist($ville);
            ++$ajoutees;
        }

        $this->entityManager->flush();

        $io->success(sprintf(
            '%d villes ajoutées, %d ignorées (déjà présentes pour ce nom et ce département).',
            $ajoutees,
            $ignorees,
        ));

        return Command::SUCCESS;
    }

    /**
     * @return list<array{0: string, 1: int, 2: string}>
     */
    private static function getVilles(): array
    {
        return array_merge(
            self::dept('77', [
        ["Melun", 0],
        ["Maincy", 5],
        ["Vaux-le-Pénil", 5],
        ["Rubelles", 6],
        ["La Rochette", 6],
        ["Livry-sur-Seine", 7],
        ["Dammarie-les-Lys", 7],
        ["Voisenon", 8],
        ["Boissettes", 8],
        ["Boissise-la-Bertrand", 9],
        ["Moisenay", 10],
        ["Cesson", 10],
        ["Vert-Saint-Denis", 11],
        ["Le Mée-sur-Seine", 11],
        ["Seine-Port", 12],
        ["Boissise-le-Roi", 12],
        ["Saint-Germain-Laxis", 12],
        ["Montereau-sur-le-Jard", 13],
        ["Sivry-Courtry", 13],
        ["Blandy", 14],
        ["Saint-Fargeau-Ponthierry", 15],
        ["Pringy", 15],
        ["Réau", 16],
        ["Nandy", 17],
        ["Savigny-le-Temple", 17],
        ["Champeaux", 17],
        ["Saint-Méry", 18],
        ["Crisenoy", 18],
        ["Limoges-Fourches", 19],
        ["Lieusaint", 20],
        ["Moissy-Cramayel", 21],
        ["Guignes", 21],
        ["Fouju", 22],
        ["Yèbles", 23],
        ["Champdeuil", 23],
        ["Soignolles-en-Brie", 24],
        ["Solers", 24],
        ["Combs-la-Ville", 25],
        ["Coubert", 25],
        ["Grisy-Suisnes", 26],
        ["Brie-Comte-Robert", 27],
        ["Fontainebleau", 28],
        ["Samois-sur-Seine", 28],
        ["Avon", 29],
        ["Héricy", 30],
        ["Vulaines-sur-Seine", 31],
        ["Chartrettes", 31],
        ["Bois-le-Roi", 32],
        ["Chailly-en-Bière", 32],
        ["Barbizon", 33],
        ["Perthes", 34],
        ["Fleury-en-Bière", 35],
        ["Arbonne-la-Forêt", 36],
        ["Moret-Loing-et-Orvanne", 36],
        ["Thomery", 36],
        ["Veneux-les-Sablons", 37],
        ["Champagne-sur-Seine", 38],
        ["Nemours", 43],
        ["Montereau-Fault-Yonne", 43],
        ["Provins", 50],
        ["Coulommiers", 55],
        ["Meaux", 65],
        ["Torcy", 45],
        ["Noisiel", 48],
        ["Lognes", 48],
        ["Champs-sur-Marne", 50],
        ["Bussy-Saint-Georges", 50],
        ["Serris", 55],
        ["Chessy", 58],
        ["Lagny-sur-Marne", 58],
        ["Chelles", 60],
        ["Claye-Souilly", 65],
        ["Achères-la-Forêt", 38],
        ["Amillis", 45],
        ["Amponville", 45],
        ["Andrezel", 25],
        ["Annet-sur-Marne", 60],
        ["Armentières-en-Brie", 70],
        ["Aufferville", 45],
        ["Augers-en-Brie", 60],
        ["Aulnoy", 55],
        ["Baby", 65],
        ["Bagneaux-sur-Loing", 50],
        ["Bailly-Romainvilliers", 55],
        ["Balloy", 45],
        ["Bannost-Villegagnon", 45],
        ["Barbey", 45],
        ["Barcy", 70],
        ["Bassevelle", 80],
        ["Bazoches-lès-Bray", 45],
        ["Beauchery-Saint-Martin", 60],
        ["Beaumont-du-Gâtinais", 55],
        ["Beautheil-Saints", 45],
        ["Bellot", 75],
        ["Bernay-Vilbert", 40],
        ["Beton-Bazoches", 55],
        ["Bezalles", 50],
        ["Boisdon", 55],
        ["Boitron", 75],
        ["Bombon", 25],
        ["Bougligny", 50],
        ["Boulancourt", 45],
        ["Bouleurs", 55],
        ["Bourron-Marlotte", 35],
        ["Boutigny", 65],
        ["Bransles", 55],
        ["Bray-sur-Seine", 50],
        ["Bréau", 18],
        ["Brou-sur-Chantereine", 55],
        ["Burcy", 55],
        ["Bussières", 80],
        ["Bussy-Saint-Martin", 48],
        ["Cannes-Écluse", 40],
        ["Carnetin", 60],
        ["Cély", 35],
        ["Cerneux", 65],
        ["Chaintreaux", 55],
        ["Chalautre-la-Grande", 70],
        ["Chalautre-la-Petite", 65],
        ["Chalifert", 58],
        ["Châtenay-sur-Seine", 45],
        ["Châtillon-la-Borde", 18],
        ["Châtres", 35],
        ["Chauconin-Neufmontiers", 65],
        ["Chauffry", 65],
        ["Chaumes-en-Brie", 35],
        ["Chevru", 55],
        ["Chevry-Cossigny", 35],
        ["Choisy-en-Brie", 60],
        ["Citry", 80],
        ["Clos-Fontaine", 40],
        ["Cocherel", 75],
        ["Compans", 70],
        ["Congis-sur-Thérouanne", 75],
        ["Couilly-Pont-aux-Dames", 55],
        ["Coulombs-en-Valois", 85],
        ["Coupvray", 58],
        ["Courcelles-en-Bassée", 40],
        ["Courchamp", 55],
        ["Courpalay", 40],
        ["Courquetaine", 30],
        ["Courtacon", 55],
        ["Courtomer", 35],
        ["Crécy-la-Chapelle", 55],
        ["Crégy-lès-Meaux", 65],
        ["Crèvecœur-en-Brie", 50],
        ["Crouy-sur-Ourcq", 85],
        ["Dagny", 50],
        ["Dammartin-en-Goële", 75],
        ["Dammartin-sur-Tigeaux", 50],
        ["Darvault", 45],
        ["Dhuisy", 80],
        ["Diant", 45],
        ["Donnemarie-Dontilly", 45],
        ["Dormelles", 40],
        ["Douy-la-Ramée", 75],
        ["Échouboulains", 25],
        ["Égligny", 45],
        ["Égreville", 55],
        ["Émerainville", 50],
        ["Épisy", 40],
        ["Esbly", 60],
        ["Étrépilly", 75],
        ["Évry-Grégy-sur-Yerre", 25],
        ["Faremoutiers", 55],
        ["Favières", 45],
        ["Faÿ-lès-Nemours", 50],
        ["Férolles-Attilly", 35],
        ["Ferrières-en-Brie", 45],
        ["Flagy", 45],
        ["Fontaine-Fourches", 55],
        ["Fontaine-le-Port", 18],
        ["Fontains", 35],
        ["Fontenailles", 25],
        ["Fontenay-Trésigny", 40],
        ["Forfry", 80],
        ["Forges", 35],
        ["Fresnes-sur-Marne", 65],
        ["Frétoy", 50],
        ["Fromont", 45],
        ["Garentreville", 50],
        ["Gastins", 40],
        ["Germigny-l'Évêque", 70],
        ["Germigny-sous-Coulombs", 80],
        ["Gesvres-le-Chapitre", 75],
        ["Giremoutiers", 60],
        ["Gironville", 50],
        ["Gouaix", 55],
        ["Gouvernes", 55],
        ["Grandpuits-Bailly-Carrois", 30],
        ["Gravon", 35],
        ["Gretz-Armainvilliers", 40],
        ["Grez-sur-Loing", 40],
        ["Grisy-sur-Seine", 50],
        ["Guérard", 55],
        ["Guercheville", 45],
        ["Guermantes", 50],
        ["Gurcy-le-Châtel", 50],
        ["Hautefeuille", 55],
        ["Hermé", 60],
        ["Hondevilliers", 85],
        ["Ichy", 50],
        ["Isles-les-Meldeuses", 75],
        ["Isles-lès-Villenoy", 60],
        ["Iverny", 70],
        ["Jablines", 60],
        ["Jaignes", 80],
        ["Jouarre", 75],
        ["Jouy-le-Châtel", 45],
        ["Jouy-sur-Morin", 65],
        ["Juilly", 70],
        ["La Celle-sur-Morin", 55],
        ["La Chapelle-Gauthier", 25],
        ["La Chapelle-Iger", 40],
        ["La Chapelle-la-Reine", 45],
        ["La Chapelle-Moutils", 65],
        ["La Croix-en-Brie", 45],
        ["La Ferté-Gaucher", 70],
        ["La Ferté-sous-Jouarre", 80],
        ["La Genevraye", 40],
        ["La Grande-Paroisse", 35],
        ["La Houssaye-en-Brie", 45],
        ["La Madeleine-sur-Loing", 50],
        ["Larchant", 45],
        ["Laval-en-Brie", 35],
        ["Le Châtelet-en-Brie", 15],
        ["Le Mesnil-Amelot", 75],
        ["Le Pin", 60],
        ["Le Plessis-aux-Bois", 75],
        ["Le Plessis-Feu-Aussoux", 50],
        ["Les Chapelles-Bourbon", 45],
        ["Les Écrennes", 20],
        ["Les Marêts", 60],
        ["Les Ormes-sur-Voulzie", 55],
        ["Lescherolles", 70],
        ["Lesches", 60],
        ["Lésigny", 35],
        ["Lissy", 20],
        ["Liverdy-en-Brie", 35],
        ["Lizines", 55],
        ["Longperrier", 75],
        ["Longueville", 55],
        ["Lorrez-le-Bocage-Préaux", 55],
        ["Louan-Villegruis-Fontaine", 70],
        ["Luisetaines", 45],
        ["Lumigny-Nesles-Ormeaux", 50],
        ["Luzancy", 85],
        ["Machault", 20],
        ["Maisoncelles-en-Brie", 60],
        ["Maison-Rouge", 55],
        ["Marchémoret", 75],
        ["Marcilly", 75],
        ["Mareuil-lès-Meaux", 60],
        ["Marles-en-Brie", 40],
        ["Marolles-en-Brie", 50],
        ["Mary-sur-Marne", 80],
        ["Mauperthuis", 55],
        ["Mauregard", 75],
        ["May-en-Multien", 90],
        ["Meigneux", 40],
        ["Melz-sur-Seine", 65],
        ["Méry-sur-Marne", 85],
        ["Messy", 65],
        ["Misy-sur-Yonne", 45],
        ["Mitry-Mory", 70],
        ["Montévrain", 55],
        ["Montceaux-lès-Meaux", 70],
        ["Montcourt-Fromonville", 45],
        ["Montdauphin", 80],
        ["Montenils", 75],
        ["Montgé-en-Goële", 75],
        ["Monthyon", 70],
        ["Montigny-le-Guesdier", 50],
        ["Montigny-Lencoup", 40],
        ["Montigny-sur-Loing", 40],
        ["Montmachoux", 45],
        ["Montolivet", 80],
        ["Mouroux", 55],
        ["Moussy-le-Neuf", 80],
        ["Moussy-le-Vieux", 75],
        ["Mouy-sur-Seine", 50],
        ["Nanteau-sur-Essonne", 45],
        ["Nanteau-sur-Lunain", 50],
        ["Nanteuil-lès-Meaux", 65],
        ["Nanteuil-sur-Marne", 85],
        ["Nantouillet", 70],
        ["Neufmoutiers-en-Brie", 45],
        ["Noisy-Rudignon", 45],
        ["Noisy-sur-École", 40],
        ["Nonville", 45],
        ["Ocquerre", 80],
        ["Oissery", 75],
        ["Orly-sur-Morin", 75],
        ["Ormesson", 55],
        ["Ozouer-le-Voulgis", 30],
        ["Ozouer-le-Repos", 25],
        ["Paley", 50],
        ["Pamfou", 25],
        ["Paroy", 55],
        ["Passy-sur-Seine", 60],
        ["Pécy", 45],
        ["Penchard", 70],
        ["Pézarches", 50],
        ["Pierre-Levée", 75],
        ["Poigny", 55],
        ["Poincy", 65],
        ["Poligny", 50],
        ["Pommeuse", 55],
        ["Pomponne", 55],
        ["Pontault-Combault", 45],
        ["Pontcarré", 45],
        ["Précy-sur-Marne", 65],
        ["Presles-en-Brie", 35],
        ["Puisieux", 75],
        ["Quiers", 30],
        ["Quincy-Voisins", 60],
        ["Rampillon", 35],
        ["Rebais", 75],
        ["Recloses", 40],
        ["Remauville", 55],
        ["Reuil-en-Brie", 80],
        ["Roissy-en-Brie", 45],
        ["Rouilly", 55],
        ["Rozay-en-Brie", 45],
        ["Saâcy-sur-Marne", 85],
        ["Saint-Augustin", 55],
        ["Saint-Barthélemy", 75],
        ["Saint-Brice", 60],
        ["Saint-Cyr-sur-Morin", 80],
        ["Saint-Denis-lès-Rebais", 75],
        ["Saint-Fiacre", 60],
        ["Saint-Germain-Laval", 35],
        ["Saint-Germain-sur-École", 35],
        ["Saint-Germain-sous-Doue", 70],
        ["Saint-Hilliers", 55],
        ["Saint-Jean-les-Deux-Jumeaux", 80],
        ["Saint-Just-en-Brie", 40],
        ["Saint-Léger", 70],
        ["Saint-Loup-de-Naud", 60],
        ["Saint-Mammès", 40],
        ["Saint-Mard", 75],
        ["Saint-Martin-des-Champs", 70],
        ["Saint-Ouen-en-Brie", 25],
        ["Saint-Pathus", 80],
        ["Saint-Pierre-lès-Nemours", 45],
        ["Saint-Sauveur-lès-Bray", 50],
        ["Saint-Sauveur-sur-École", 25],
        ["Sainte-Aulde", 90],
        ["Sammeron", 80],
        ["Samoreau", 35],
        ["Sancy", 60],
        ["Savins", 55],
        ["Sept-Sorts", 80],
        ["Servon", 30],
        ["Signy-Signets", 80],
        ["Souppes-sur-Loing", 55],
        ["Tancrou", 85],
        ["Thieux", 75],
        ["Thorigny-sur-Marne", 58],
        ["Tigeaux", 50],
        ["Touquin", 50],
        ["Tournan-en-Brie", 40],
        ["Tousson", 45],
        ["Trilbardou", 65],
        ["Trilport", 70],
        ["Ury", 40],
        ["Vaires-sur-Marne", 55],
        ["Valence-en-Brie", 30],
        ["Vanvillé", 50],
        ["Varennes-sur-Seine", 40],
        ["Varreddes", 70],
        ["Vaucourtois", 60],
        ["Vaudoy-en-Brie", 45],
        ["Vendrest", 85],
        ["Verdelot", 85],
        ["Verneuil-l'Étang", 25],
        ["Vernou-la-Celle-sur-Seine", 35],
        ["Villebéon", 55],
        ["Villecerf", 40],
        ["Villemaréchal", 45],
        ["Villemer", 40],
        ["Villenauxe-la-Petite", 60],
        ["Villeneuve-le-Comte", 50],
        ["Villeneuve-Saint-Denis", 50],
        ["Villeneuve-sous-Dammartin", 75],
        ["Villeneuve-sur-Bellot", 85],
        ["Villiers-en-Bière", 15],
        ["Villiers-Saint-Georges", 60],
        ["Villiers-sous-Grez", 45],
        ["Villiers-sur-Morin", 55],
        ["Villuis", 55],
        ["Vimpelles", 50],
        ["Vinantes", 70],
        ["Vincy-Manœuvre", 75],
        ["Voinsles", 50],
        ["Voulangis", 55],
            ]),
            self::dept('91', [
        ["Abbéville-la-Rivière", 65],
        ["Angerville", 80],
        ["Angervilliers", 65],
        ["Arpajon", 50],
        ["Arrancourt", 70],
        ["Athis-Mons", 45],
        ["Authon-la-Plaine", 75],
        ["Auvernaux", 22],
        ["Auvers-Saint-Georges", 55],
        ["Avrainville", 50],
        ["Ballainvilliers", 50],
        ["Ballancourt-sur-Essonne", 30],
        ["Baulne", 40],
        ["Bièvres", 60],
        ["Blandy", 65],
        ["Boigneville", 55],
        ["Bois-Herpin", 65],
        ["Boissy-la-Rivière", 65],
        ["Boissy-le-Cutté", 50],
        ["Boissy-le-Sec", 65],
        ["Boissy-sous-Saint-Yon", 50],
        ["Bondoufle", 35],
        ["Boullay-les-Troux", 70],
        ["Bouray-sur-Juine", 45],
        ["Boussy-Saint-Antoine", 30],
        ["Boutigny-sur-Essonne", 40],
        ["Bouville", 55],
        ["Brétigny-sur-Orge", 45],
        ["Breuillet", 55],
        ["Breux-Jouy", 55],
        ["Brières-les-Scellés", 60],
        ["Briis-sous-Forges", 60],
        ["Brunoy", 32],
        ["Bruyères-le-Châtel", 55],
        ["Buno-Bonnevaux", 50],
        ["Cerny", 40],
        ["Chalo-Saint-Mars", 70],
        ["Chalou-Moulineux", 80],
        ["Chamarande", 50],
        ["Champcueil", 25],
        ["Champlan", 55],
        ["Champmotteux", 55],
        ["Chatignonville", 80],
        ["Cheptainville", 45],
        ["Chevannes", 25],
        ["Chilly-Mazarin", 50],
        ["Congerville-Thionville", 80],
        ["Corbeil-Essonnes", 25],
        ["Corbreuse", 70],
        ["Courances", 25],
        ["Courcouronnes", 35],
        ["Courdimanche-sur-Essonne", 45],
        ["Courson-Monteloup", 60],
        ["Crosne", 40],
        ["D'Huison-Longueville", 45],
        ["Dannemois", 30],
        ["Dourdan", 70],
        ["Draveil", 40],
        ["Écharcon", 25],
        ["Égly", 50],
        ["Épinay-sous-Sénart", 35],
        ["Épinay-sur-Orge", 45],
        ["Étampes", 65],
        ["Étiolles", 28],
        ["Étréchy", 55],
        ["Évry-Courcouronnes", 30],
        ["Fleury-Mérogis", 40],
        ["Fontenay-le-Vicomte", 30],
        ["Fontenay-lès-Briis", 60],
        ["Forges-les-Bains", 65],
        ["Gif-sur-Yvette", 65],
        ["Gironville-sur-Essonne", 55],
        ["Gometz-la-Ville", 65],
        ["Gometz-le-Châtel", 65],
        ["Grigny", 40],
        ["Guillerval", 75],
        ["Guigneville-sur-Essonne", 45],
        ["Igny", 60],
        ["Itteville", 35],
        ["Janville-sur-Juine", 50],
        ["Janvry", 65],
        ["Juvisy-sur-Orge", 45],
        ["Lardy", 45],
        ["La Ferté-Alais", 40],
        ["La Forêt-le-Roi", 75],
        ["La Forêt-Sainte-Croix", 65],
        ["La Norville", 50],
        ["La Ville-du-Bois", 50],
        ["Le Coudray-Montceaux", 22],
        ["Le Mérévillois", 75],
        ["Le Plessis-Pâté", 45],
        ["Le Val-Saint-Germain", 65],
        ["Les Granges-le-Roi", 75],
        ["Les Molières", 70],
        ["Les Ulis", 65],
        ["Leudeville", 45],
        ["Leuville-sur-Orge", 50],
        ["Limours", 70],
        ["Linas", 50],
        ["Lisses", 30],
        ["Longjumeau", 50],
        ["Longpont-sur-Orge", 50],
        ["Maisse", 50],
        ["Marcoussis", 55],
        ["Marolles-en-Beauce", 70],
        ["Marolles-en-Hurepoix", 45],
        ["Massy", 60],
        ["Mennecy", 30],
        ["Méréville", 75],
        ["Mérobert", 70],
        ["Mespuits", 60],
        ["Milly-la-Forêt", 40],
        ["Moigny-sur-École", 35],
        ["Mondeville", 30],
        ["Monnerville", 75],
        ["Montgeron", 35],
        ["Montlhéry", 50],
        ["Morangis", 50],
        ["Morigny-Champigny", 60],
        ["Morsang-sur-Orge", 45],
        ["Morsang-sur-Seine", 20],
        ["Nainville-les-Roches", 25],
        ["Nozay", 55],
        ["Ollainville", 50],
        ["Oncy-sur-École", 40],
        ["Ormoy", 28],
        ["Ormoy-la-Rivière", 65],
        ["Orsay", 65],
        ["Orveau", 45],
        ["Palaiseau", 60],
        ["Paray-Vieille-Poste", 50],
        ["Pecqueuse", 70],
        ["Plessis-Saint-Benoist", 75],
        ["Prunay-sur-Essonne", 55],
        ["Puiselet-le-Marais", 70],
        ["Pussay", 80],
        ["Quincy-sous-Sénart", 30],
        ["Richarville", 70],
        ["Ris-Orangis", 35],
        ["Roinville", 65],
        ["Roinvilliers", 75],
        ["Roussigny", 75],
        ["Rouvres-Saint-Jean", 75],
        ["Saclas", 70],
        ["Saclay", 65],
        ["Saint-Aubin", 70],
        ["Saint-Chéron", 60],
        ["Saint-Cyr-la-Rivière", 65],
        ["Saint-Cyr-sous-Dourdan", 70],
        ["Saint-Escobille", 75],
        ["Saint-Germain-lès-Arpajon", 50],
        ["Saint-Germain-lès-Corbeil", 25],
        ["Saint-Hilaire", 65],
        ["Saint-Jean-de-Beauregard", 65],
        ["Saint-Maurice-Montcouronne", 60],
        ["Saint-Michel-sur-Orge", 45],
        ["Saint-Pierre-du-Perray", 22],
        ["Saint-Sulpice-de-Favières", 55],
        ["Saint-Vrain", 40],
        ["Sainte-Geneviève-des-Bois", 45],
        ["Saintry-sur-Seine", 22],
        ["Saulx-les-Chartreux", 55],
        ["Savigny-sur-Orge", 45],
        ["Sermaise", 60],
        ["Soisy-sur-École", 30],
        ["Soisy-sur-Seine", 30],
        ["Souzy-la-Briche", 55],
        ["Tigery", 25],
        ["Torfou", 55],
        ["Valpuiseaux", 60],
        ["Varennes-Jarcy", 28],
        ["Vaugrigneuse", 60],
        ["Vauhallan", 65],
        ["Verrières-le-Buisson", 60],
        ["Vert-le-Grand", 35],
        ["Vert-le-Petit", 35],
        ["Videlles", 40],
        ["Vigneux-sur-Seine", 40],
        ["Villabé", 28],
        ["Villebon-sur-Yvette", 60],
        ["Villeconin", 60],
        ["Villejust", 60],
        ["Villemoisson-sur-Orge", 50],
        ["Villeneuve-sur-Auvers", 55],
        ["Villiers-le-Bâcle", 70],
        ["Villiers-sur-Orge", 50],
        ["Viry-Châtillon", 42],
        ["Wissous", 55],
        ["Yerres", 35],
            ]),
            self::dept('94', [
        ["Ablon-sur-Seine", 45],
        ["Alfortville", 50],
        ["Arcueil", 60],
        ["Boissy-Saint-Léger", 35],
        ["Bonneuil-sur-Marne", 42],
        ["Bry-sur-Marne", 55],
        ["Cachan", 60],
        ["Champigny-sur-Marne", 50],
        ["Charenton-le-Pont", 55],
        ["Chennevières-sur-Marne", 45],
        ["Chevilly-Larue", 55],
        ["Choisy-le-Roi", 50],
        ["Créteil", 45],
        ["Fontenay-sous-Bois", 60],
        ["Fresnes", 60],
        ["Gentilly", 60],
        ["Ivry-sur-Seine", 55],
        ["Joinville-le-Pont", 55],
        ["L'Haÿ-les-Roses", 60],
        ["La Queue-en-Brie", 40],
        ["Le Kremlin-Bicêtre", 60],
        ["Le Perreux-sur-Marne", 55],
        ["Le Plessis-Trévise", 50],
        ["Limeil-Brévannes", 38],
        ["Maisons-Alfort", 50],
        ["Mandres-les-Roses", 30],
        ["Marolles-en-Brie", 35],
        ["Nogent-sur-Marne", 58],
        ["Noiseau", 42],
        ["Orly", 50],
        ["Ormesson-sur-Marne", 45],
        ["Périgny", 30],
        ["Rungis", 55],
        ["Saint-Mandé", 60],
        ["Saint-Maur-des-Fossés", 50],
        ["Saint-Maurice", 55],
        ["Santeny", 30],
        ["Sucy-en-Brie", 40],
        ["Thiais", 50],
        ["Valenton", 40],
        ["Villecresnes", 30],
        ["Villejuif", 60],
        ["Villeneuve-le-Roi", 45],
        ["Villeneuve-Saint-Georges", 40],
        ["Villiers-sur-Marne", 55],
        ["Vincennes", 60],
        ["Vitry-sur-Seine", 55],
            ]),
            self::dept('93', [
        ["Aubervilliers", 70],
        ["Aulnay-sous-Bois", 70],
        ["Bagnolet", 65],
        ["Bobigny", 65],
        ["Bondy", 65],
        ["Clichy-sous-Bois", 60],
        ["Coubron", 60],
        ["Drancy", 70],
        ["Dugny", 75],
        ["Épinay-sur-Seine", 80],
        ["Gagny", 60],
        ["Gournay-sur-Marne", 55],
        ["L'Île-Saint-Denis", 80],
        ["La Courneuve", 75],
        ["Le Blanc-Mesnil", 70],
        ["Le Bourget", 75],
        ["Le Pré-Saint-Gervais", 65],
        ["Le Raincy", 65],
        ["Les Lilas", 65],
        ["Les Pavillons-sous-Bois", 65],
        ["Livry-Gargan", 65],
        ["Montfermeil", 60],
        ["Montreuil", 60],
        ["Neuilly-Plaisance", 55],
        ["Neuilly-sur-Marne", 55],
        ["Noisy-le-Grand", 50],
        ["Noisy-le-Sec", 65],
        ["Pantin", 65],
        ["Pierrefitte-sur-Seine", 80],
        ["Romainville", 65],
        ["Rosny-sous-Bois", 60],
        ["Saint-Denis", 75],
        ["Saint-Ouen-sur-Seine", 75],
        ["Sevran", 70],
        ["Stains", 75],
        ["Tremblay-en-France", 75],
        ["Vaujours", 65],
        ["Villemomble", 60],
        ["Villepinte", 70],
        ["Villetaneuse", 80],
            ]),
            self::dept('92', [
        ["Antony", 60],
        ["Asnières-sur-Seine", 75],
        ["Bagneux", 65],
        ["Bois-Colombes", 75],
        ["Boulogne-Billancourt", 70],
        ["Bourg-la-Reine", 60],
        ["Châtenay-Malabry", 65],
        ["Châtillon", 65],
        ["Chaville", 75],
        ["Clamart", 70],
        ["Clichy", 75],
        ["Colombes", 80],
        ["Courbevoie", 80],
        ["Fontenay-aux-Roses", 65],
        ["Garches", 80],
        ["Gennevilliers", 80],
        ["Issy-les-Moulineaux", 70],
        ["La Garenne-Colombes", 80],
        ["Levallois-Perret", 75],
        ["Malakoff", 70],
        ["Marnes-la-Coquette", 80],
        ["Meudon", 75],
        ["Montrouge", 65],
        ["Nanterre", 85],
        ["Neuilly-sur-Seine", 80],
        ["Le Plessis-Robinson", 65],
        ["Puteaux", 80],
        ["Rueil-Malmaison", 85],
        ["Saint-Cloud", 75],
        ["Sceaux", 60],
        ["Sèvres", 75],
        ["Suresnes", 80],
        ["Vanves", 70],
        ["Vaucresson", 85],
        ["Ville-d'Avray", 80],
        ["Villeneuve-la-Garenne", 85],
            ]),
            self::dept('75', [
        ["Paris 1er (Louvre)", 62],
        ["Paris 2e (Bourse)", 63],
        ["Paris 3e (Temple)", 62],
        ["Paris 4e (Hôtel-de-Ville)", 60],
        ["Paris 5e (Panthéon)", 58],
        ["Paris 6e (Luxembourg)", 60],
        ["Paris 7e (Invalides)", 65],
        ["Paris 8e (Élysée)", 66],
        ["Paris 9e (Opéra)", 65],
        ["Paris 10e", 65],
        ["Paris 11e", 60],
        ["Paris 12e (Gare de Lyon / Bercy)", 55],
        ["Paris 13e", 55],
        ["Paris 14e", 60],
        ["Paris 15e", 65],
        ["Paris 16e", 70],
        ["Paris 17e", 70],
        ["Paris 18e", 70],
        ["Paris 19e", 65],
        ["Paris 20e", 62],
            ]),
            self::dept('95', [
        ["Ableiges", 100],
        ["Aincourt", 120],
        ["Ambleville", 125],
        ["Amenucourt", 130],
        ["Andilly", 90],
        ["Argenteuil", 85],
        ["Arnouville", 80],
        ["Arronville", 105],
        ["Arthies", 120],
        ["Asnières-sur-Oise", 100],
        ["Attainville", 90],
        ["Auvers-sur-Oise", 105],
        ["Avernes", 115],
        ["Baillet-en-France", 95],
        ["Banthelu", 120],
        ["Beauchamp", 100],
        ["Beaumont-sur-Oise", 105],
        ["Belloy-en-France", 95],
        ["Bernes-sur-Oise", 105],
        ["Berville", 115],
        ["Bessancourt", 100],
        ["Bezons", 85],
        ["Boisemont", 100],
        ["Boissy-l'Aillerie", 100],
        ["Bonneuil-en-France", 80],
        ["Bouffémont", 95],
        ["Bouqueval", 85],
        ["Bray-et-Lû", 130],
        ["Bréançon", 110],
        ["Brignancourt", 110],
        ["Bruyères-sur-Oise", 105],
        ["Buhy", 130],
        ["Cergy", 105],
        ["Champagne-sur-Oise", 105],
        ["Charmont", 120],
        ["Chars", 115],
        ["Châtenay-en-France", 90],
        ["Chaumontel", 100],
        ["Chauvry", 95],
        ["Chennevières-lès-Louvres", 85],
        ["Cormeilles-en-Parisis", 95],
        ["Cormeilles-en-Vexin", 110],
        ["Courcelles-sur-Viosne", 105],
        ["Courdimanche", 105],
        ["Deuil-la-Barre", 85],
        ["Domont", 90],
        ["Écouen", 85],
        ["Enghien-les-Bains", 85],
        ["Ennery", 105],
        ["Épiais-lès-Louvres", 85],
        ["Épiais-Rhus", 110],
        ["Épinay-Champlâtreux", 95],
        ["Eragny", 100],
        ["Ermont", 95],
        ["Ézanville", 90],
        ["Fontenay-en-Parisis", 90],
        ["Fosses", 95],
        ["Franconville", 95],
        ["Frémainville", 115],
        ["Frémécourt", 110],
        ["Frépillon", 100],
        ["Frouville", 110],
        ["Gadancourt", 120],
        ["Garges-lès-Gonesse", 80],
        ["Genainville", 125],
        ["Génicourt", 110],
        ["Gonesse", 80],
        ["Goussainville", 85],
        ["Gouzangrez", 115],
        ["Grisy-les-Plâtres", 110],
        ["Groslay", 85],
        ["Guiry-en-Vexin", 120],
        ["Haravilliers", 115],
        ["Haute-Isle", 130],
        ["Hérouville-en-Vexin", 110],
        ["Hodent", 125],
        ["Jagny-sous-Bois", 95],
        ["Jouy-le-Moutier", 105],
        ["L'Isle-Adam", 105],
        ["La Chapelle-en-Vexin", 130],
        ["La Frette-sur-Seine", 100],
        ["Labbeville", 110],
        ["Lassy", 95],
        ["Le Bellay-en-Vexin", 120],
        ["Le Heaulme", 115],
        ["Le Mesnil-Aubry", 90],
        ["Le Perchay", 110],
        ["Le Plessis-Bouchard", 95],
        ["Le Plessis-Gassot", 85],
        ["Le Plessis-Luzarches", 95],
        ["Le Thillay", 85],
        ["Livilliers", 110],
        ["Longuesse", 115],
        ["Louvres", 90],
        ["Luzarches", 95],
        ["Magny-en-Vexin", 130],
        ["Mareil-en-France", 95],
        ["Margency", 90],
        ["Marines", 115],
        ["Marly-la-Ville", 95],
        ["Maudétour-en-Vexin", 130],
        ["Menouville", 110],
        ["Menucourt", 110],
        ["Mériel", 105],
        ["Méry-sur-Oise", 105],
        ["Moisselles", 90],
        ["Montgeroult", 105],
        ["Montigny-lès-Cormeilles", 100],
        ["Montlignon", 95],
        ["Montmagny", 85],
        ["Montmorency", 90],
        ["Montreuil-sur-Epte", 135],
        ["Montsoult", 95],
        ["Mours", 105],
        ["Nerville-la-Forêt", 100],
        ["Nesles-la-Vallée", 110],
        ["Neuilly-en-Vexin", 120],
        ["Neuville-sur-Oise", 105],
        ["Nointel", 105],
        ["Noisy-sur-Oise", 105],
        ["Nucourt", 125],
        ["Omerville", 130],
        ["Osny", 105],
        ["Parmain", 105],
        ["Persan", 105],
        ["Pierrelaye", 100],
        ["Piscop", 85],
        ["Pontoise", 105],
        ["Presles", 100],
        ["Puiseux-en-France", 90],
        ["Roissy-en-France", 80],
        ["Ronquerolles", 105],
        ["Sagy", 115],
        ["Saint-Brice-sous-Forêt", 85],
        ["Saint-Clair-sur-Epte", 135],
        ["Saint-Cyr-en-Arthies", 125],
        ["Saint-Gervais", 125],
        ["Saint-Gratien", 90],
        ["Saint-Leu-la-Forêt", 95],
        ["Saint-Martin-du-Tertre", 100],
        ["Saint-Ouen-l'Aumône", 105],
        ["Saint-Prix", 95],
        ["Saint-Witz", 95],
        ["Sannois", 90],
        ["Sarcelles", 85],
        ["Seraincourt", 115],
        ["Seugy", 100],
        ["Soisy-sous-Montmorency", 90],
        ["Survilliers", 95],
        ["Taverny", 100],
        ["Théméricourt", 115],
        ["Theuville", 110],
        ["Vaudherland", 85],
        ["Vauréal", 105],
        ["Vétheuil", 130],
        ["Viarmes", 100],
        ["Vienne-en-Arthies", 125],
        ["Vigny", 115],
        ["Villaines-sous-Bois", 95],
        ["Villeron", 90],
        ["Villers-en-Arthies", 125],
        ["Villiers-Adam", 100],
        ["Villiers-le-Bel", 85],
        ["Villiers-le-Sec", 95],
        ["Wy-dit-Joli-Village", 120],
            ]),
            self::dept('78', [
        ["Ablis", 85],
        ["Achères", 95],
        ["Adainville", 100],
        ["Aigremont", 90],
        ["Allainville", 85],
        ["Andelu", 100],
        ["Andrésy", 100],
        ["Arnouville-lès-Mantes", 110],
        ["Auffargis", 80],
        ["Auffreville-Brasseuil", 110],
        ["Aulnay-sur-Mauldre", 100],
        ["Auteuil", 95],
        ["Autouillet", 100],
        ["Bailly", 80],
        ["Bazainville", 105],
        ["Bazemont", 100],
        ["Bazoches-sur-Guyonne", 90],
        ["Béhoust", 100],
        ["Bennecourt", 120],
        ["Beynes", 95],
        ["Blaru", 125],
        ["Boinville-en-Mantois", 110],
        ["Boinville-le-Gaillard", 90],
        ["Boinvilliers", 110],
        ["Bois-d'Arcy", 80],
        ["Boissets", 110],
        ["Boissy-Mauvoisin", 115],
        ["Boissy-sans-Avoir", 95],
        ["Bonnelles", 75],
        ["Bonnières-sur-Seine", 120],
        ["Bouafle", 100],
        ["Bougival", 90],
        ["Bourdonné", 105],
        ["Breuil-Bois-Robert", 110],
        ["Bréval", 120],
        ["Brueil-en-Vexin", 110],
        ["Buc", 75],
        ["Buchelay", 110],
        ["Bullion", 75],
        ["Carrières-sous-Poissy", 100],
        ["Carrières-sur-Seine", 90],
        ["Cernay-la-Ville", 75],
        ["Chambourcy", 95],
        ["Chanteloup-les-Vignes", 100],
        ["Chapet", 100],
        ["Châteaufort", 75],
        ["Chatou", 90],
        ["Chavenay", 90],
        ["Chevreuse", 75],
        ["Choisel", 75],
        ["Civry-la-Forêt", 105],
        ["Clairefontaine-en-Yvelines", 75],
        ["Coignières", 80],
        ["Condé-sur-Vesgre", 110],
        ["Conflans-Sainte-Honorine", 100],
        ["Courgent", 115],
        ["Cravent", 120],
        ["Crespières", 95],
        ["Croissy-sur-Seine", 90],
        ["Dammartin-en-Serve", 115],
        ["Dampierre-en-Yvelines", 75],
        ["Davron", 90],
        ["Drocourt", 120],
        ["Ecquevilly", 100],
        ["Élancourt", 80],
        ["Émancé", 85],
        ["Épône", 105],
        ["Évecquemont", 105],
        ["Favrieux", 115],
        ["Feucherolles", 90],
        ["Flacourt", 115],
        ["Flexanville", 100],
        ["Flins-sur-Seine", 100],
        ["Follainville-Dennemont", 115],
        ["Fontenay-le-Fleury", 75],
        ["Fontenay-Mauvoisin", 115],
        ["Fontenay-Saint-Père", 115],
        ["Fourqueux", 90],
        ["Freneuse", 120],
        ["Gaillon-sur-Montcient", 105],
        ["Galluis", 95],
        ["Gambais", 105],
        ["Gambaiseuil", 110],
        ["Garancières", 95],
        ["Gargenville", 105],
        ["Gazeran", 80],
        ["Gommecourt", 125],
        ["Goupillières", 100],
        ["Goussonville", 110],
        ["Grandchamp", 105],
        ["Gressey", 110],
        ["Grosrouvre", 100],
        ["Guernes", 120],
        ["Guerville", 110],
        ["Guyancourt", 75],
        ["Hardricourt", 105],
        ["Hargeville", 105],
        ["Herbeville", 95],
        ["Hermeray", 90],
        ["Houdan", 110],
        ["Houilles", 90],
        ["Jambville", 110],
        ["Jeufosse", 125],
        ["Jouars-Pontchartrain", 85],
        ["Jouy-en-Josas", 75],
        ["Jouy-Mauvoisin", 115],
        ["Jumeauville", 105],
        ["La Boissière-École", 100],
        ["La Celle-les-Bordes", 75],
        ["La Celle-Saint-Cloud", 85],
        ["La Falaise", 100],
        ["La Hauteville", 100],
        ["La Queue-les-Yvelines", 95],
        ["Le Chesnay-Rocquencourt", 80],
        ["Le Mesnil-le-Roi", 95],
        ["Le Mesnil-Saint-Denis", 80],
        ["Le Pecq", 90],
        ["Le Perray-en-Yvelines", 80],
        ["Le Port-Marly", 90],
        ["Le Tartre-Gaudran", 115],
        ["Les Alluets-le-Roi", 95],
        ["Les Bréviaires", 90],
        ["Les Clayes-sous-Bois", 80],
        ["Les Essarts-le-Roi", 80],
        ["Les Loges-en-Josas", 75],
        ["Les Mureaux", 105],
        ["Lévis-Saint-Nom", 80],
        ["Limay", 110],
        ["Limetz-Villez", 125],
        ["Lommoye", 120],
        ["Longnes", 110],
        ["Longvilliers", 75],
        ["Louveciennes", 90],
        ["Magnanville", 110],
        ["Magny-les-Hameaux", 75],
        ["Maisons-Laffitte", 95],
        ["Mantes-la-Jolie", 115],
        ["Mantes-la-Ville", 110],
        ["Mareil-le-Guyon", 90],
        ["Mareil-Marly", 90],
        ["Mareil-sur-Mauldre", 100],
        ["Marly-le-Roi", 90],
        ["Maule", 100],
        ["Maulette", 110],
        ["Maurecourt", 100],
        ["Maurepas", 80],
        ["Médan", 100],
        ["Méré", 95],
        ["Mézières-sur-Seine", 105],
        ["Mézy-sur-Seine", 105],
        ["Millemont", 95],
        ["Milon-la-Chapelle", 75],
        ["Mittainville", 95],
        ["Moisson", 125],
        ["Mondreville", 115],
        ["Montainville", 95],
        ["Montalet-le-Bois", 110],
        ["Montchauvet", 110],
        ["Montesson", 90],
        ["Montfort-l'Amaury", 95],
        ["Montigny-le-Bretonneux", 75],
        ["Morainvilliers", 95],
        ["Mousseaux-sur-Seine", 120],
        ["Mulcent", 110],
        ["Nézel", 100],
        ["Noisy-le-Roi", 85],
        ["Notre-Dame-de-la-Mer", 125],
        ["Oinville-sur-Montcient", 105],
        ["Orgeval", 95],
        ["Orphin", 90],
        ["Orsonville", 90],
        ["Paray-Douaville", 85],
        ["Perdreauville", 115],
        ["Plaisir", 85],
        ["Poigny-la-Forêt", 85],
        ["Poissy", 95],
        ["Pontchartrain", 85],
        ["Porcheville", 110],
        ["Port-Villez", 125],
        ["Prunay-en-Yvelines", 85],
        ["Prunay-le-Temple", 105],
        ["Raizeux", 90],
        ["Rambouillet", 85],
        ["Rennemoulin", 80],
        ["Richebourg", 110],
        ["Rochefort-en-Yvelines", 75],
        ["Rocquencourt", 80],
        ["Rolleboise", 120],
        ["Rosay", 110],
        ["Rosny-sur-Seine", 115],
        ["Sailly", 115],
        ["Saint-Arnoult-en-Yvelines", 80],
        ["Saint-Cyr-l'École", 75],
        ["Saint-Forget", 75],
        ["Saint-Germain-de-la-Grange", 90],
        ["Saint-Germain-en-Laye", 90],
        ["Saint-Hilarion", 85],
        ["Saint-Illiers-la-Ville", 120],
        ["Saint-Illiers-le-Bois", 120],
        ["Saint-Lambert", 75],
        ["Saint-Léger-en-Yvelines", 95],
        ["Saint-Martin-de-Bréthencourt", 85],
        ["Saint-Martin-des-Champs", 110],
        ["Saint-Martin-la-Garenne", 115],
        ["Saint-Nom-la-Bretèche", 90],
        ["Saint-Rémy-lès-Chevreuse", 75],
        ["Saint-Rémy-l'Honoré", 85],
        ["Sartrouville", 95],
        ["Saulx-Marchais", 100],
        ["Senlisse", 75],
        ["Septeuil", 105],
        ["Soindres", 110],
        ["Sonchamp", 85],
        ["Tacoignières", 105],
        ["Tessancourt-sur-Aubette", 110],
        ["Thiverval-Grignon", 90],
        ["Thoiry", 100],
        ["Tilly", 115],
        ["Toussus-le-Noble", 75],
        ["Trappes", 80],
        ["Triel-sur-Seine", 105],
        ["Vaux-sur-Seine", 105],
        ["Vélizy-Villacoublay", 70],
        ["Verneuil-sur-Seine", 105],
        ["Vernouillet", 105],
        ["Versailles", 75],
        ["Vert", 110],
        ["Vicq", 95],
        ["Vieille-Église-en-Yvelines", 85],
        ["Villennes-sur-Seine", 100],
        ["Villepreux", 85],
        ["Villette", 110],
        ["Villiers-le-Mahieu", 100],
        ["Villiers-Saint-Frédéric", 90],
        ["Viroflay", 75],
        ["Voisins-le-Bretonneux", 75],
            ]),
            self::dept('89', [["Sens", 65]]),
            self::dept('10', [["Troyes", 100]]),
            self::dept('45', [["Orléans", 130]]),
        );
    }

    /**
     * @param list<array{0: string, 1: int}> $rows
     *
     * @return list<array{0: string, 1: int, 2: string}>
     */
    private static function dept(string $departement, array $rows): array
    {
        return array_map(
            static fn (array $row): array => [$row[0], $row[1], $departement],
            $rows,
        );
    }
}
